[package]
name = "librgboy"
version = "0.1.0"
authors = ["Yushi Omote <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = { version = "1.2", features = ["spin_no_std"] }
log = "0.4"
hashmap_core = "0.1"